@GestionHuacales.Api_HostAddress = https://localhost:7047

###

POST https://gestionhuacalesapi.azurewebsites.net/api/entradahuacales
Content-Type: application/json

{
  "nombreCliente": "Enel",
  "huacales": [
    {
      "idTipo": 1,
      "cantidad": 1,
      "precio": 100
    }
  ]
}

###
