@GestionHuacales.Api_HostAddress = https://localhost:7047

###

POST https://gestionhuacalesapi.azurewebsites.net/api/entradahuacales
Content-Type: application/json

{
  "nombreCliente": "Enel",
  "huacales": [
    {
      "idTipo": 1,
      "cantidad": 1,
      "precio": 100
    }
  ]
}

###

POST {{GestionHuacales.Api_HostAddress}}/api/movimientos
Content-Type: application/json

{
  "partidaId": 1,
  "jugador": "X",
  "posicionFila": 0,
  "posicionColumna": 0
}

###
