// <auto-generated />
using System;
using GestionHuacales.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionHuacales.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251014001114_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradaHuacales");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacalesDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdTipo");

                    b.ToTable("EntradaHuacalesDetalles");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.TiposHuacales", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 2,
                            Descripcion = "Rojo",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 3,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 4,
                            Descripcion = "Rojo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacalesDetalle", b =>
                {
                    b.HasOne("GestionHuacales.Api.Models.EntradaHuacales", "entradaHuacales")
                        .WithMany("entradaHuacalesDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionHuacales.Api.Models.TiposHuacales", "tiposHuacales")
                        .WithMany("EntradaHuacalesDetalle")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entradaHuacales");

                    b.Navigation("tiposHuacales");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacales", b =>
                {
                    b.Navigation("entradaHuacalesDetalle");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradaHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
