// <auto-generated />
using System;
using GestionHuacales.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionHuacales.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251019171744_Tareas")]
    partial class Tareas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradaHuacales");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacalesDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdTipo");

                    b.ToTable("EntradaHuacalesDetalles");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Derrotas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Empates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Victorias")
                        .HasColumnType("INTEGER");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Movimientos", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicionColumna")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosicionFila")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovimientoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Partidas", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoPartida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoTablero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jugador1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Jugador2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnoJugadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartidaId");

                    b.HasIndex("GanadorId");

                    b.HasIndex("Jugador1Id");

                    b.HasIndex("Jugador2Id");

                    b.HasIndex("TurnoJugadorId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.TiposHuacales", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 2,
                            Descripcion = "Rojo",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 3,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            IdTipo = 4,
                            Descripcion = "Rojo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacalesDetalle", b =>
                {
                    b.HasOne("GestionHuacales.Api.Models.EntradaHuacales", "entradaHuacales")
                        .WithMany("entradaHuacalesDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionHuacales.Api.Models.TiposHuacales", "tiposHuacales")
                        .WithMany("EntradaHuacalesDetalle")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entradaHuacales");

                    b.Navigation("tiposHuacales");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Movimientos", b =>
                {
                    b.HasOne("GestionHuacales.Api.Models.Jugadores", "Jugador")
                        .WithMany("Movimientos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionHuacales.Api.Models.Partidas", "Partida")
                        .WithMany("Movimientos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Partidas", b =>
                {
                    b.HasOne("GestionHuacales.Api.Models.Jugadores", "Ganador")
                        .WithMany("PartidasGanadas")
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionHuacales.Api.Models.Jugadores", "Jugador1")
                        .WithMany("PartidasComoJugador1")
                        .HasForeignKey("Jugador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionHuacales.Api.Models.Jugadores", "Jugador2")
                        .WithMany("PartidasComoJugador2")
                        .HasForeignKey("Jugador2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionHuacales.Api.Models.Jugadores", "TurnoJugador")
                        .WithMany()
                        .HasForeignKey("TurnoJugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");

                    b.Navigation("TurnoJugador");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.EntradaHuacales", b =>
                {
                    b.Navigation("entradaHuacalesDetalle");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Jugadores", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("PartidasComoJugador1");

                    b.Navigation("PartidasComoJugador2");

                    b.Navigation("PartidasGanadas");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.Partidas", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("GestionHuacales.Api.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradaHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
